### PR TITLE
fix(auth): remove excessive warning and typo

### LINKED ISSUE #209: auth logging is too chatty
I think that the new auth logging is too chatty:

```rust
        } else if token_type == TokenType::Auth {
            // not configured `auth_tokens` means that the user is allowed to access the endpoints
            warn!("auth_tokens not configured, allowing the request without auth header");
            user_tokens.insert(token_type);
        }
```

Doesn't this mean that this is logged/printed for every request, if no auth_tokens are set? So, iff one doesn't use auth tokens, their log is spammed with these messages.

This shouldn't be a warning, rather an info message or debug message. IMO, there doesn't need to be a message at all.

### PR DESCRIPTION
**Pull request by tessus**
## Description

Iff one doesn't use auth tokens, their log is spammed with warning messages.
This change removes the warning message.

It also fixes a small typo.

## Motivation and Context

Fixes #209

## How Has This Been Tested?

cargo test
fixtures

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [x] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [x] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tessus** [comment]
Something's off with the shuttle deploy action. But I don't think a shuttle version should be deployed when creating a PR. Or is this a test shuttle instance (not prod)?

**Review by orhun — APPROVED** [review]
LGTM, thanks!

**Comment by orhun** [comment]
> Something's off with the shuttle deploy action.

Yeah, it shouldn't deploy. I think the following condition is not working:

```
      - name: Deploy
        if: |
          ${{ startsWith(github.event.ref, 'refs/tags/v') ||
            github.event_name == 'workflow_dispatch' ||
            steps.changes.outputs.manifest == 'true'
          }}
```

Are you interested in looking into it by any chance?

**Comment by tessus** [comment]
I would be, but I do not have a shuttle account. Not sure how to test any changes on my fork.
I might be able to look into it within the next few weeks (I will also have to create a shuttle account and API key). Although during the holidays it's always busy.

**Comment by orhun** [comment]
Alright, no problem. I think it is just enough to test that condition on GitHub Actions. I will just create an immediate release for the changes in this PR now and we can look into that later I guess.

**Pull request merged**
