### PR TITLE
feat(log): switch to `tracing` for logging

### LINKED ISSUE #161: Use `tracing` instead of `log`
Since `rustypaste` is a web service, it would be nice to integrate `tracing_subscriber::fmt` instead of plain logging via `env_logger`.

### PR DESCRIPTION
**Pull request by woshilapin**
resolves #161

## Description

Only changing `env_logger` into `tracing-subscriber`. It should support the same configuration with `RUST_LOG` (and more, if we convert from `log` to `tracing` later).

## Motivation and Context

See #161.

## How Has This Been Tested?

Logging are usually not tested. If any test would be needed, could you give some pointers?

## Changelog Entry

````
### Changed

- Changes the logger formatter to `tracing-subscriber`
````
-->

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [ ] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [x] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [x] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by orhun** [comment]
Looks great! We only need one change, see https://github.com/orhun/rustypaste/issues/161#issuecomment-1769170790

**Comment by woshilapin** [comment]
> Looks great! We only need one change, see [#161 (comment)](https://github.com/orhun/rustypaste/issues/161#issuecomment-1769170790)

@orhun Sure thing, here it is in [a404dfc](https://github.com/orhun/rustypaste/pull/163/commits/a404dfc35331c63f6c9ea007c68972740ca3dd69).

**Comment by orhun** [comment]
LGTM, just one thing, can you configure tracing subscriber so that the default log level will be `INFO`? Because now if you run `rustypaste` then you get no output. We should somehow use `INFO` as default to not break CLI backwards compatibility.

**Comment by woshilapin** [comment]
> LGTM, just one thing, can you configure tracing subscriber so that the default log level will be `INFO`? Because now if you run `rustypaste` then you get no output. We should somehow use `INFO` as default to not break CLI backwards compatibility.

@orhun Good point. Done in [b18610c](https://github.com/orhun/rustypaste/pull/163/commits/b18610ce457dfcd3dab37f73951bef7fa8968025) thanks to https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#method.from_default_env.

**Review by orhun — APPROVED** [review]
Super awesome!

**Pull request merged**
