### PR TITLE
feat(server): add landing page

### PR DESCRIPTION
**Pull request by TheTechRobo**
Fixes orhun/rustypaste#13

The default landing page is set as a const in the binary, but is configurable with the server.landing_page key. Should the key be in another section (i.e. not `[server]`? Handling is added for when the config file doesn't have any landing page. I updated the default config.toml.

### CODE REVIEW

**Comment by TheTechRobo** [comment]
I kinda want to add a `{}` you can do to insert the repository URL. But I'm not sure how to format that - Rust doesn't accept `format!(a_string, another_string)` where `a_string` is `Hello, {}!` and `another_string` is `world`

**Comment by TheTechRobo** [comment]
I just did that, lmk if I shouldn't.

**Comment by TheTechRobo** [comment]
Maybe I should also add how soon pastes expire.

**Comment by orhun** [comment]
> The default landing page is set as a const in the binary, but is configurable with the server.landing_page key. Should the key be in another section (i.e. not `[server]`? Handling is added for when the config file doesn't have any landing page. I updated the default config.toml.

I think it is fine 👌🏼 

> I kinda want to add a `{}` you can do to insert the repository URL. But I'm not sure how to format that - Rust doesn't accept `format!(a_string, another_string)` where `a_string` is `Hello, {}!` and `another_string` is `world`
> 
> Should I just do a `replace` on the string?

Hmm, it looks fine for now. I might change the behavior after this PR is merged though. I'm not sure if I want duplicate landing page text as both constant and in the config file. However, that's a concern for later.

> Maybe I should also add how soon pastes expire.

That would be nice, please add that as well 👍🏼

**Comment by orhun** [comment]
CI is failing, can you update tests and apply formatting?

**Comment by TheTechRobo** [comment]
> I'm not sure if I want duplicate landing page text as both constant and in the config file. However, that's a concern for later.

I thought about that, but then won't existing configurations break?

> > Maybe I should also add how soon pastes expire.
> That would be nice, please add that as well 👍🏼

Right now it's hardcoded. I'm not sure what the best way to go about this is.

**Comment by TheTechRobo** [comment]
> CI is failing, can you update tests and apply formatting?

All sorted.

**Comment by TheTechRobo** [comment]
It appears the only test I broke was test_index, which makes sense. Every other failing test is broken on master.

**Comment by orhun** [comment]
> It appears the only test I broke was test_index, which makes sense (since that's all I changed). Every other failing test is broken on master.

Tests should be run with `cargo test --test-threads 1`. `test_index` was failing because the config was not given via `app_data` while initializing the server. I fixed it in ee93fbc761a62a0ed98b4a12aee3e524ebb22a2f

I also changed the behavior in c91ffecbaa00ddb2f2c374169f37905868e1d253, I think it makes sense to redirect to the GitHub repository (as before) if landing page is not specified.

**Review by orhun — APPROVED** [review]

**Comment by TheTechRobo** [comment]
> test_index was failing because the config was not given via app_data while initializing the server.

I knew that one, just wasn't sure how to fix it. Thanks for the --test-threads tip and thanks for merging!

**Pull request merged**
