### PR TITLE
Test CI

### PR DESCRIPTION
**Pull request by tessus**
# Testing CI

Currently the same as #246

First theory: something is cached on gh and for some reason 246 can't get out of this state

2nd theory: default expiry has to be set explicitly in tests

3rd theory: tarpulin has a side effect

### CODE REVIEW

**Comment by tessus** [comment]
Ok, I think we have to contact the tarpulin devs.

**Comment by tessus** [comment]
Closing this again, after figuring out what the issue is.

/ref https://github.com/xd009642/tarpaulin/issues/1488

**Comment by orhun** [comment]
Thanks for investigating this!

**Comment by tessus** [comment]
You're welcome.

**Pull request closed without merging**
